# Generated by Django 2.2 on 2019-04-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=100)),
                ('Amount_Required', models.IntegerField()),
                ('Buisness_Type', models.CharField(choices=[('FS', 'Food Service'), ('MS', 'Medical'), ('CT', 'Construction'), ('TE', 'Technology'), ('SP', 'Sports'), ('CL', 'Clothing')], default='Technology', max_length=100)),
                ('Age', models.IntegerField()),
                ('Approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
    ]
