# Generated by Django 2.2 on 2019-04-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
