# Generated by Django 2.2 on 2019-04-18 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20190418_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='Approved',
        ),
    ]
